spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: root
        data : classpath:sql/*.sql
        hikari:
            data-source-properties:
              prepStmtCacheSize: 250
              prepStmtCacheSqlLimit: 2048
              useServerPrepStmts: true
    jpa:
        database: MYSQL
        show_sql: true
        hibernate:
          ddl-auto : update
        properties:
            hibernate.generate_statistics: false
            hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
    data:
        elasticsearch:
            cluster-name: demo-owish
            cluster-nodes: 127.0.0.1:9300
server :
    port: 7080